#docker-compose up [--build]
#Docker compose para poder levantar el contenedor con el comando docker compose up
version: "3"

services:
  app:
    tty: true
    build: .
    ports:
      - "8080:8080"
